### ISSUE TITLE
Header do checkout durante alteração de dados do pedido

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/my-orders#5]
A alteração de dados do pedido deve entregar um texto diferente de acordo com a opção selecionada no MyOrders.

Para cada tipo de alteração, o header deve trazer:

**Alterar dados de pagamento**
**Alterar dados de entrega**
**Alterar dados de pessoais**

Exemplo:

![image](https://cloud.githubusercontent.com/assets/3229933/21201276/7db6d3d0-c231-11e6-9d00-0423a8989b0d.png)

**Comment by dfosco** [comment]
@zehfernandes Acha que precisamos indicar melhor (ou de forma mais específica) qual ação o usuário deve realizar no checkout durante a alteração do pedido?

Não fiz nenhum estilo mais detalhado por que algumas lojas customizam muito o checkout, então me parece que entregar o dado mais “cru” faz mais sentido

**Comment by gugiserman** [comment]
E se o usuário resolver abrir outra área do checkout (ex: fui trocar o endereço e resolvi mudar o telefone em seguida, ao invés de seguir pro payment)? Continua o título de trocar endereço?

**Comment by dfosco** [comment]
Boa @gugiserman, não tinha pensado nisso — deixamos só com “Alterar dados do pedido” então 👌
