### ISSUE TITLE
States do botão de edição/cancelamento

### ISSUE THREAD

**Issue by dfosco** [vtex-apps/my-orders#8]
Replicando aqui a pergunta do Slack. Dado que temos esses conjuntos de estados para um pedido:

**Alterar** ✅   | **Cancelar**✅ 
**Alterar** ❌   | **Cancelar**✅
**Alterar** ❌   | **Cancelar**❌

Acho que deveríamos refletir dessa forma no card de pedido:

![pasted_image_at_2016_12_26_19_08_360](https://cloud.githubusercontent.com/assets/3229933/21525783/a59493f8-cd06-11e6-8555-64b82f45d7ce.png)

Esconder o botão quando alteração/cancelamento estiverem indisponíveis deixa a UI inconsistente e pode confundir os usuários.

**Comment by dfosco** [comment]
Pergunta adicional: Remover a opção de alteração do botão causa a mesma inconsistência?

**Comment by zehfernandes** [comment]
Muitas lojas vão querer esconder o botão como fazem hoje com o cancelar.
ex: eletrolux. não deixa o usuário cancelar via UI.

Sou a favor de se o usuário não puder mais cancelar nem alterar o botão deve sumir e nossa UI não pode ficar inconsistente

**Comment by dfosco** [comment]
Interessante. 

Nesse caso o texto `Alterar ou Cancelar pedido` não atenderia eles e teriam que mudar o texto do botão via JS (considerando que já removeram a opção de cancelar dentro da página de alteração).

Não seria melhor deixarmos dois botões separados mesmo?

**Comment by gugiserman** [comment]
Vamos ter que voltar aos 2 botões pra atender os casos de se alguma loja quiser desabilitar uma das duas funcionalidades?

**Comment by zehfernandes** [comment]
@dfosco @gugiserman Faz muito sentido. Ainda mais que agora temos a tela com porque do cancelamento e no fluxo Alterar/Cancelar ela não aparece

**Comment by gugiserman** [comment]
@zehfernandes Remover a opção de cancelamento da página de edição e deixar os dois botões separados na lista de pedidos cada um com a sua página?
